### ISSUE TITLE
code to be pushed

### ISSUE THREAD

**Issue by alistair-broomhead** [russel/pip_extras#1]
Hi @alyphen I think there's a commit on your computer that I forgot to push, that adds 0.0.5 which renames the executable to pip_upgrade and sorts out the Readme and authors etc

**Comment by russel** [comment]
@alyphen @alistair-broomhead I have made a new repository russel/pip_update with just the pip_update material in it with s/extras/update/. Hopefully, the missing push stuff can be added there.

**Comment by alyphen** [comment]
Hi Alistair,

Sorry for my delayed response, I've been building a new PC over the last 
day so haven't really had a chance to check e-mails.

I'll look at pushing it tomorrow evening.

**Comment by alistair-broomhead** [comment]
Cool @alyphen if you push what's there as a new branch on this repo I can look at the diff to see what's still useful now that we're splitting things

**Comment by alyphen** [comment]
@alistair-broomhead I've pushed your changes to the 'rename' branch

**Comment by alistair-broomhead** [comment]
cool - I've applied those changes plus some more on russel/pip_upgrade
